In [1]:
import numpy as np
import pandas as pd

# Task1

In [87]:
monday = pd.Series({'Alice':8,'Bob':6,'David':7})
tuesday = pd.Series({'Bob':8,'Carol':5,'David':6})
wednesday = pd.Series({'Alice':7,'Carol':8,'David':5})
print(monday,tuesday,wednesday, sep='\n')

Alice    8
Bob      6
David    7
dtype: int64
Bob      8
Carol    5
David    6
dtype: int64
Alice    7
Carol    8
David    5
dtype: int64

# Task2

In [79]:
total_hours = monday.add(tuesday, fill_value=0).add(wednesday, fill_value=0)
print(total_hours)

Alice    15.0
Bob      14.0
Carol    13.0
David    18.0
dtype: float64

# Task3

In [82]:
print(total_hours.idxmax())

David

# Task4

In [88]:
shifts = {'Worker':['Alice','Bob','Carol','David'],
             'Mon':[8,6,0,7],
             'tue':[0,8,5,6],
             'wed':[7,0,8,5]}

shifts_df = pd.DataFrame(shifts)
print(shifts_df)

  Worker  Mon  tue  wed
0  Alice    8    0    7
1    Bob    6    8    0
2  Carol    0    5    8
3  David    7    6    5

# Exercises

In [81]:
worker_name = input("input workers name")

if worker_name in total_hours:
    print(f"{worker_name}:{total_hours[worker_name]} hours worked")

input workers name Bob

Bob:14.0 hours worked

In [78]:
cou = pd.Series({'usa':1776, 'canada':1867, 'mexico':1821})
print(cou)

usa       1776
canada    1867
mexico    1821
dtype: int64

In [2]:
pd.Series([10, 100, 15, 35])

0     10
1    100
2     15
3     35
dtype: int64

In [3]:
np.array([10, 100, 15, 35])

array([ 10, 100,  15,  35])

In [5]:
s1 = pd.Series([1, 2, 3])
print(s1)

0    1
1    2
2    3
dtype: int64

In [7]:
s1[1]

np.int64(2)

In [14]:
countries = {'usa':1776, 'canada':1867, 'mexico':1821}
s = pd.Series(countries)
print(s)

usa       1776
canada    1867
mexico    1821
dtype: int64

In [18]:
years       = [1776, 1867, 1821]
label_index = ['USA', 'CANADA', 'MEXICO']

s2 = pd.Series(index=label_index, data=years)
print(s2)

USA       1776
CANADA    1867
MEXICO    1821
dtype: int64

In [19]:
print(countries.keys())

Index(['USA', 'CANADA', 'MEXICO'], dtype='object')

In [20]:
print(list(countries.keys()))

['USA', 'CANADA', 'MEXICO']

In [23]:
countries.iloc[0]

C:\Users\germa\AppData\Local\Temp\ipykernel_28112\1395873769.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  countries[0]

np.int64(1776)

In [24]:
countries.loc['CANADA']

np.int64(1867)

In [27]:
first  = pd.Series({'Japan': 100, 'China': 450, 'USA': 250})
second = pd.Series({'Brazil': 70, 'China': 350, 'USA': 200})
result = first + second
print(result)

Brazil      NaN
China     800.0
Japan       NaN
USA       450.0
dtype: float64

In [29]:
result = first.add(second, fill_value=0)
print(result)

Brazil     70.0
China     800.0
Japan     100.0
USA       450.0
dtype: float64

In [30]:
s_float = pd.Series({'Japan': 100.99, 'China': 450, 'USA': 250})
print(s_float.dtype)

s_int = pd.Series([1, 2, 3])
print(s_int.dtype)

float64
int64

In [31]:
tel_aviv = pd.Series({'milk': 10, 'bread': 5,  'eggs': 12, 'butter': 3})
haifa    = pd.Series({'milk': 8,  'eggs': 6,  'water': 20})
modiin   = pd.Series({'bread': 15, 'butter': 7, 'water': 10, 'juice': 5})

In [33]:
total_stock =tel_aviv.add(haifa, fill_value=0).add(modiin, fill_value=0)

print(total_stock)

bread     20.0
butter    10.0
eggs      18.0
juice      5.0
milk      18.0
water     30.0
dtype: float64

In [38]:
product = input("Enter product name: ")

if product in total_stock:
    print(f"{product}: {int(total_stock[product])} units across all stores")
else:
    print(f"{product} is not stocked in any store")

Enter product name:  milk

milk: 18 units across all stores

In [40]:
print(total_stock["bread"])

20.0

In [41]:
tips_df = pd.read_csv('tips.csv')
tips_df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [42]:
tips_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object
 3   smoker            244 non-null    object
 4   day               244 non-null    object
 5   time              244 non-null    object
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object
 9   CC Number         244 non-null    int64
 10  Payment ID        244 non-null    object
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB

In [45]:
print(tips_df.columns)
print(tips_df.index)
print(len(tips_df))

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')
RangeIndex(start=0, stop=244, step=1)
244

In [60]:
tips_df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [55]:
tips_df.tail(5)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [58]:
tips_df.describe()

       total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

In [64]:
tips_df['tip']

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [62]:
tips_df[['tip','day']]

      tip   day
0    1.01   Sun
1    1.66   Sun
2    3.50   Sun
3    3.31   Sun
4    3.61   Sun
..    ...   ...
239  5.92   Sat
240  2.00   Sat
241  2.00   Sat
242  1.75   Sat
243  3.00  Thur

[244 rows x 2 columns]

In [66]:
tips_df['new_column'] = tips_df['tip'] + tips_df['total_bill']
tips_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object
 3   smoker            244 non-null    object
 4   day               244 non-null    object
 5   time              244 non-null    object
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object
 9   CC Number         244 non-null    int64
 10  Payment ID        244 non-null    object
 11  new_column        244 non-null    float64
dtypes: float64(4), int64(2), object(6)
memory usage: 23.0+ KB

In [71]:
tips_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 243 entries, 0 to 243
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        243 non-null    float64
 1   tip               243 non-null    float64
 2   sex               243 non-null    object
 3   smoker            243 non-null    object
 4   day               243 non-null    object
 5   time              243 non-null    object
 6   size              243 non-null    int64
 7   price_per_person  243 non-null    float64
 8   Payer Name        243 non-null    object
 9   CC Number         243 non-null    int64
 10  Payment ID        243 non-null    object
 11  new_column        243 non-null    float64
dtypes: float64(4), int64(2), object(6)
memory usage: 32.8+ KB

In [73]:
tips_df.drop('tip', axis=1, inplace=True)

In [74]:
tips_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 243 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        243 non-null    float64
 1   sex               243 non-null    object
 2   smoker            243 non-null    object
 3   day               243 non-null    object
 4   time              243 non-null    object
 5   size              243 non-null    int64
 6   price_per_person  243 non-null    float64
 7   Payer Name        243 non-null    object
 8   CC Number         243 non-null    int64
 9   Payment ID        243 non-null    object
 10  new_column        243 non-null    float64
dtypes: float64(3), int64(2), object(6)
memory usage: 30.9+ KB